// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-categories.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/data/category-list.ts
var categoryList = [
  { name: "Bebidas", slug: "bebidas" },
  { name: "Carne", slug: "carne" },
  { name: "Cereais", slug: "cereais" },
  { name: "Charcutaria", slug: "charcutaria" },
  { name: "Cogumelos", slug: "cogumelos" },
  { name: "Conservas", slug: "conservas" },
  { name: "Ervas arom\xE1ticas", slug: "ervas-aromaticas" },
  { name: "Flores", slug: "flores" },
  { name: "Fruta", slug: "fruta" },
  { name: "Frutos Secos", slug: "frutos-secos" },
  { name: "Gorduras", slug: "gorduras" },
  { name: "Hal\xF3fitas", slug: "halofitas" },
  { name: "Hort\xEDcolas", slug: "horticolas" },
  { name: "Latic\xEDnios", slug: "laticinios" },
  { name: "Leguminosas", slug: "leguminosas" },
  { name: "Mel", slug: "mel" },
  { name: "\xD3leos essenciais", slug: "oleos-essenciais" },
  { name: "Outros produtos", slug: "outros-produtos" },
  { name: "Ovos", slug: "ovos" },
  { name: "P\xE3o artesanal", slug: "pao-artesanal" },
  { name: "Salgados", slug: "salgados" },
  { name: "Temperos e especiarias", slug: "temperos-e-especiarias" }
];

// src/lib/mcp/tools/list-categories.ts
var list_categories_default = defineTool({
  name: "list_categories",
  title: "List product categories",
  description: "List all product categories available on FarmConnect (Bebidas, Carne, Fruta, Hort\xEDcolas, etc.).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const rows = categoryList.map((c) => ({ name: c.name, slug: c.slug }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { categories: rows }
    };
  }
});

// src/lib/mcp/tools/search-farmers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var search_farmers_default = defineTool2({
  name: "search_farmers",
  title: "Search farmers",
  description: "Search FarmConnect farmers (producers) by farm name or address text. Returns public farm profiles.",
  inputSchema: {
    query: z.string().trim().optional().describe("Text to match against company name or address. Omit to list recent farmers."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    let q = supabase.from("farmer_public").select("id, company_name, address, description, website, pickup_days").eq("registration_step", 2).limit(limit ?? 10);
    if (query && query.length > 0) {
      const like = `%${query}%`;
      q = q.or(`company_name.ilike.${like},address.ilike.${like}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { farmers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_products_default = defineTool3({
  name: "list_products",
  title: "List products",
  description: "Browse active FarmConnect products. Optionally filter by category name or farmer id.",
  inputSchema: {
    category: z2.string().trim().optional().describe("Category name, e.g. 'Fruta', 'Hort\xEDcolas'."),
    farmer_id: z2.string().uuid().optional().describe("Restrict to one farmer."),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, farmer_id, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    let q = supabase.from("products").select("id, name, category, client_price, unit, stock_quantity, is_organic, delivery_mode, farmer_id").eq("active", true).limit(limit ?? 20);
    if (category) q = q.eq("category", category);
    if (farmer_id) q = q.eq("farmer_id", farmer_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool4({
  name: "list_my_orders",
  title: "List my orders",
  description: "List orders belonging to the signed-in FarmConnect user (as client or as farmer).",
  inputSchema: {
    status: z3.enum(["awaiting_pickup", "delivered", "expired", "cancelled"]).optional(),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let q = supabase.from("orders").select("id, status, total, pickup_code, pickup_deadline, paid_at, created_at, farmer_id, client_id").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ntqaoqwclijbtrblttyj";
var mcp_default = defineMcp({
  name: "farmconnect-mcp",
  title: "FarmConnect MCP",
  version: "0.1.0",
  instructions: "Tools for FarmConnect, a Portuguese proximity marketplace connecting clients to local farmers. Use `list_categories` to see product categories, `search_farmers` to find producers, `list_products` to browse the catalog, and `list_my_orders` to inspect the signed-in user's orders.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_categories_default, search_farmers_default, list_products_default, list_my_orders_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
